
FROM mcr.microsoft.com/mssql/server:2017-latest
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Password1
ENV MSSQL_PID=Developer
ENV MSSQL_TCP_PORT=1433
WORKDIR /src
COPY ./migration/ViajaPlus_Query/SQLQueryCreationViajaPlustables.sql ./SQLQueryCreationViajaPlustables.sql
RUN (/opt/mssql/bin/sqlservr --accept-eula & ) | grep -q "Service Broker manager has started" && sleep 30 && /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U sa -P Password1 -i SQLQueryCreationViajaPlustables.sql